language: generic
sudo: required
services:
- docker
env:
  - DOCKER_USERNAME=tommywenjiezhang
before_install:
- docker build -t tommywenjiezhang/docker_python_pipeline_setup .
script:
- docker run -e CI=true --name docker_python_pipeline_setup tommywenjiezhang/docker_python_pipeline_setup
  python3 -m unittest tests.py
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
