#!/bin/bash
docker login --username="$DOCKER_USERNAME" --password=$(heroku auth:token) registry.heroku.com
heroku container:push web --app docker-python-pipeline
heroku container:release web --app docker-python-pipeline
heroku open --app docker-python-pipeline
